# -*- coding: utf-8 -*-
"""ModelizadoIA_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qp1f7FnAQqHkmx_1OSogGtGSlnvVR_Kg

# Bibliotecas necesarias
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
from torch import optim
from torch import nn
from torch.utils.data import DataLoader
from tqdm import tqdm

import torchvision
import torch.nn.functional as F
import torchvision.datasets as datasets
import torchvision.transforms as transforms

import torchmetrics

"""##Creación de los lotes de entrenamiento."""

batch_size = 60

train_dataset = datasets.MNIST(root="dataset/", download=True, train=True, transform=transforms.ToTensor())

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)

test_dataset = datasets.MNIST(root="dataset/", download=True, train=False, transform=transforms.ToTensor())

test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=True)

"""##Aspecto del lote."""

def imshow(img):
  npimg = img.numpy()
  plt.imshow(np.transpose(npimg, (1, 2, 0)))
  plt.show()

# conseguir algunas imagenes de entrenamiento
dataiter = iter(train_loader)
images, labels = next(dataiter)
labels

#mostrar imagenes
imshow(torchvision.utils.make_grid(images))

"""##Definición de la arquitectura CNN"""

class CNN(nn.Module):
  def __init__(self, in_channels, num_classes):
    """
    Construyendo los bloques de la Red Neuronal Convolucional

    Paramétros:
      *in_channels: numero de canales de entrada (para imagenes en escala de grisis, 1)
      *num_classes: numero de clases a predecir. En nuestro problema, 10(i.e digits desde 0 a 9)
    """
    super(CNN, self).__init__()
    #Primera Capa de Convolución
    self.conv1 = nn.Conv2d(in_channels=in_channels, out_channels=8, kernel_size=3, padding=1)
    #Max Capa Pooling
    self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
    #Segunda Capa Convolucional
    self.conv2 = nn.Conv2d(in_channels=8, out_channels=16, kernel_size=3, padding=1)
    #Capa completamente conectada
    self.fc1 = nn.Linear(16*7*7, num_classes)

  def forward(self, x):
    """
       Define el paso hacia adelante de la red neuronal.

       Parametros:
           x: Input tensor.

       Retornos:
           torch.Tensor
               La salida del tensor luego pasa por la red neuronal.
    """
    x = F.relu(self.conv1(x))  # Aplica la primera primera capa de convolución y la activación por ReLU
    x = self.pool(x)           # Aplica max pooling
    x = F.relu(self.conv2(x))  # Aplica la segunda capa de concolución y la activación por ReLU
    x = self.pool(x)           # Aplica max pooling
    x = x.reshape(x.shape[0], -1)  # Aplana el tensor
    x = self.fc1(x)            # Aplica la capa completamente conectada
    return x

"""
Entrenamos el modelo en GPU siempre que sea posible, caso contrario se la entrena en CPU
       """
device = "cuda" if torch.cuda.is_available() else "cpu"

model = CNN(in_channels=1, num_classes=10).to(device)
print(model)

"""##Entrenamiento del modelo

"""

# Definición de la función de perdida
criterion = nn.CrossEntropyLoss()

# Definición del optimizador
optimizer = optim.Adam(model.parameters(), lr=0.001)

#Se hace una iteración sobre 10 épocas
num_epochs=10
for epoch in range(num_epochs):
 # Iteramos sobre los lotes de entrenamiento
   print(f"Epoch [{epoch + 1}/{num_epochs}]")

   for batch_index, (data, targets) in enumerate(tqdm(train_loader)):
       data = data.to(device)
       targets = targets.to(device)
       scores = model(data)
       loss = criterion(scores, targets)
       optimizer.zero_grad()
       loss.backward()
       optimizer.step()

"""##Evaluación del modelo"""

# Seteo de la precisión multiclase del modelo
acc = torchmetrics.Accuracy(task="multiclass",num_classes=10)
precision = torchmetrics.Precision(task="multiclass", num_classes=10)
recall = torchmetrics.Recall(task="multiclass", num_classes=10)

# Iteración sobre los lotes del dataset
model.eval()
with torch.no_grad():
   for images, labels in test_loader:
       # Obtención de las probabiloidades de predicción para cada lote de los datos de prueba
       outputs = model(images)
       _, preds = torch.max(outputs, 1)
       acc(preds, labels)
       precision(preds, labels)
       recall(preds, labels)

#Compute total test accuracy
#Computa el total de precisión de la prueba
test_accuracy = acc.compute()
print(f"Test accuracy: {test_accuracy}")

#Precisión de la prueba: 0.9857000112533569

"""##Despliegue del modelo"""

# Salvar el modelo
torch.save(model.state_dict(), 'MulticlassCNN.pth')

# Crear un nuevo modelo
loaded_model = CNN(in_channels=1, num_classes=10)

# Cargar el modelo salvado
loaded_model.load_state_dict(torch.load('MulticlassCNN.pth'))
print(loaded_model)

"""
CNN(
  (conv1): Conv2d(1, 8, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (pool): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
  (conv2): Conv2d(8, 16, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (fc1): Linear(in_features=784, out_features=10, bias=True)
)
"""